name: Scheduled Commits

on:
  schedule:
    # Define horários específicos (UTC): 00h e 06h UTC
    - cron: '0 0 * * *'
    - cron: '0 6 * * *'

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Configurar Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Criar e commitar alteração fictícia
        run: |
          echo "Última execução: $(date '+%Y-%m-%d %H:%M:%S %Z')" > last-run.txt
          git add last-run.txt
          git commit -m "Atualização automática via GitHub Actions" || echo "Nenhuma alteração para commit"
          git push || echo "Nada para enviar"
