name: Push Local Commits

on:
  schedule:
    - cron: '0 0 * * *'  # Meia-noite UTC
    - cron: '0 6 * * *'  # 06h UTC

jobs:
  push_commits:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Configurar Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push commits locais
        run: |
          git pull origin main  # Puxa as alterações do repositório remoto
          git push origin main  # Faz o push dos commits locais para o remoto
